Repository rtk-rnjn/Parrot, pull requests merged in 2022-02, with the labels that each got.

#179 Update pickup_lines.json
  extra/valentines/pickup_lines.json
Labels: enhancement, good first issue

#180 Update pickup_lines.json
  extra/valentines/pickup_lines.json
Labels: enhancement

#219 Update quote.txt
  extra/quote.txt
Labels: enhancement

#197 Add logic for `2048`
  interactions/buttons/games.py
Labels: enhancement, help wanted, good first issue

#244 TTT Ai Done
  interactions/buttons/games.py
Labels: enhancement, help wanted, maybe bug
